# fly.toml app configuration file generated for my-rss-app on 2024-09-02T00:44:20-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-rss-app'
primary_region = 'scl'

[build]

[processes]
  worker = 'python main.py'

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['worker']

[[vm]]
  size = 'shared-cpu-1x'
