interval: 600  # Intervalo en segundos
log_file: "app.log"
ifttt_webhook_url: "https://maker.ifttt.com/trigger/rss_process_completed/with/key/d_4khvEWOx-AjU2Vle6CNO"
database:
  connection_url: "postgresql://ntejedov:1Al5yWnyXIKRDCDRz9c51thpN7DVUA3m@dpg-cqtg83bv2p9s73dff6ig-a.oregon-postgres.render.com/rss_app_db"
sections:
  Youtube:
    - url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCJOdW-8tYGjzJj2t77rBmXA"
      type: "youtube"
    - url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC3_PG15cjuBIKzkEsUznQKQ"
      type: "youtube"
    - url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCP0AJJeNkFBYzegTTVbKhPg"
      type: "youtube"
    - url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCIpXj6C68YhT8Px3DGCafYA"
      type: "youtube"
  Noticias:
    - url: "https://www.idl-reporteros.pe/feed/"
      type: "rss"
    - url: "https://ojo-publico.com/rss.xml"
      type: "rss"
    - url: "https://www.vozdeamerica.com/api/zqi-qmekg-q_"
      type: "rss"
    - url: "https://laencerrona.pe/articulos/feed/"
      type: "rss"
    - url: "https://elcomercio.pe/"
      type: "web"
    - url: "https://elbuho.pe/seccion/noticias/nacional/feed/"
      type: "rss"
    - url: "https://elcomercio.pe/arc/outboundfeeds/rss/category/politica/?outputType=xml"
      type: "rss"
    - url: "https://elcomercio.pe/arc/outboundfeeds/rss/category/ultimas-noticias/?outputType=xml"
      type: "rss"
  Internacionales:
    - url: "https://www.vozdeamerica.com/api/zororegtor"
      type: "rss"
    - url: "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/america/portada"
      type: "rss"
    - url: "https://www.bbc.com/mundo"
      type: "web"
    - url: "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/ultimas-noticias/portada"
      type: "rss"
  CienciayTech:
    - url: "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/tecnologia/portada"
      type: "rss"
    - url: "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/ciencia/portada"
      type: "rss"
    - url: "https://www.perfil.com/feed/tecnologia"
      type: "rss"
    - url: "https://www.muyinteresante.com/rss/tecnologia.xml"
      type: "rss"
    - url: "http://rss.dw.com/rdf/rss-sp-cyt"
      type: "rss"
    - url: "https://hipertextual.com/tecnologia/feed"
      type: "rss"
  Curiosidades:
    - url: "https://www.muyinteresante.com/rss/curiosidades.xml"
      type: "rss"
  Mascotas:
    - url: "https://www.muyinteresante.com/rss/mascotas.xml"
      type: "rss"
  Salud:
    - url: "https://www.muyinteresante.com/rss/salud.xml"
      type: "rss"
    - url: "https://saludconlupa.com/noticias/"
      type: "web"
  CineyTV:
    - url: "https://hipertextual.com/cine-television/feed"
      type: "rss"
